### ISSUE TITLE
Using @unixroot should be $ENV{unixroot}

### ISSUE THREAD

**Issue by claunia** [bitwiseworks/cmake-os2#4] opened 2021-04-22 03:16 UTC
**Describe the bug**
Using incorrect way of resolving environment variables.

**To Reproduce**
https://github.com/bitwiseworks/cmake-os2/blob/ccd2827012623ef97f5c4386fa8d8c542763cced/Modules/Platform/os2.cmake#L13

**Expected behavior**
https://cmake.org/cmake/help/latest/variable/ENV.html

**Comment by dmik** [comment] 2021-04-23 15:26
Why do you think it is incorrect? `@unixroot` is not an environment variable, it's more of a symbolic link, or a "path rewrite rule" in terms of kLIBC/LIBCn (https://github.com/bitwiseworks/libc-os2). Can you be more specific about what you tried to achieve and failed?

**Comment by claunia** [comment] 2021-04-23 15:50
I'm not an expert on CMake and I thought that was the correct interpretation.

What I'm trying to achieve, is to compile OS/2 applications from Linux, including therefore, being able to use cmake.

**Comment by dmik** [comment] 2021-04-23 17:49
Well, it will be enough for you to just create a `/@unixroot` symbolic link on your root Linux drive and point it to a desired location for the OS/2 unixroot tree. That should work. I'm closing this as "not a bug".

**Closed as completed by dmik** 2021-04-23 17:49 UTC
